name: ci_pipeline

on:
  push:
    branches:
      - master

permissions:
  security-events: write # Must have this to allow writing to Security Tab
  contents: read 
      
jobs:
  docker_pipeline:
    uses: huynaism/reusable-workflow/.github/workflows/docker_pipeline.yml@0.1.3
    secrets: inherit