name: test

on:
  pull_request:
    branches:
      - master

permissions:
#   security-events: write # Must have this to allow writing to Security Tab
  contents: read 
      
jobs:
  testing:
    uses: huynaism/reusable-workflow/.github/workflows/test.yml@80270e25ecba401908e05c8e266931df95d0f27e
    secrets: inherit