name: test

on:
  pull_request:
    branches:
      - master

permissions:
#   security-events: write # Must have this to allow writing to Security Tab
  contents: read 
      
jobs:
  testing:
    uses: huynaism/reusable-workflow/.github/workflows/test.yml@e9e76e89ff6864a6dc2ae7ee83ce87ce23504643
    secrets: inherit