name: pr_check

on:
  pull_request:
    branches:
      - master

permissions:
#   security-events: write # Must have this to allow writing to Security Tab
  contents: read 
      
jobs:
  testing:
    uses: huynaism/reusable-workflow/.github/workflows/pr_check.yml@1.0.0
    secrets: inherit