name: test

on:
  pull_request:
  push:
    branches:
      - 'master'

permissions:
  contents: read

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Run unit tests
        run: make test
 